library("survminer")
library("ggsurvfit")
library("survival")
library("ggplot2")
library("tidyr")

inpath <- "./ACC_datasets_integration/CandidateNewBCateninTargets/input/"
outpath <- "./ACC_datasets_integration/CandidateNewBCateninTargets/output/"

# Histogram correlation gene-signature all genes
all_corr <- readRDS(file="./ACC_datasets_integration/GSEAs/pearsonCorrelation_BcateninActivationSignatureVsGene_WithPvalues.RDS")
all_corr$Correlation_value <- as.numeric(as.vector(all_corr$Correlation_value))
png(file=paste0(outpath,"Correlations_Gene_Signature.png"))
hist(all_corr$Correlation_value)
dev.off()

# Identify best correlated genes (top 50 and Pearson>0.5) -----------------
genes <- all_corr[all_corr$Correlation_value> 0.5,]$gene
write.table(file=paste0(outpath, "CorrGreater05.txt"), genes, sep="\n", quote =F, col.names = F, row.names = F)

# Identify best correlated genes with TCF/LEF TFBS evidence from iRegulon -----------------
iRegulon <- read.table(file=paste0(inpath, "/CorrGreater05_iRegulon.tsv"), header=T, sep="\t", comment.char = ";") # file generated by iRegulon software
keep <- iRegulon[grep("LEF1|TCF7|TCF7L1|TCF7L2", iRegulon$Transcription.factor),]
keep <- unique(unlist(keep$Target.genes))
keep_vec <- unlist(strsplit(keep, split=","))
keep_vec <- unique(keep_vec)  
length(keep_vec)
write.table(file=paste0(outpath, "CorrGreater05_TCFLEFTFBS.txt"), keep_vec, sep="\n", quote =F, col.names = F, row.names = F)

# Identify best correlated genes with TCF/LEF TFBS and sign FC Lefevre -----------------
Lefevre_FC <- read.table(file="./ACC_datasets_formatted/Lefevre/Metadata/SuppTable1_DEanalysis_FC_adjPvalue.txt", sep="\t", header=T)
colnames(Lefevre_FC) <- c("Gene", "FC","adj_pval")
Lefevre_FC$FC <- -(Lefevre_FC$FC) # because in original article from which these data come comparison is repressed vs expressed
genes_LefevreUp <- Lefevre_FC[((Lefevre_FC$Gene %in% keep_vec)&(Lefevre_FC$adj_pval < 0.1)&(Lefevre_FC$FC > 0)),]$Gene
length(genes_LefevreUp)
write.table(file=paste0(outpath, "CorrGreater05_TCFLEFTFBS_SignUpLefevre.txt"), keep_vec, sep="\n", quote =F, col.names = F, row.names = F)



